<a href="https://colab.research.google.com/github/Robertotheto/Introducao-TensorFlow/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao TensorFlow

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp

Criando um tensor de 0 dimensões

In [ ]:
tensor_zero_d = tf.constant(8)
print(tensor_zero_d)

tf.Tensor(8, shape=(), dtype=int32)


Criando um tensor de 1 dimensões

In [ ]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


Criando um tensor de 2 dimensões

In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


Criando um tensor de 3 dimensões

In [ ]:
tensor_tree_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],
    [[1,5,6],
    [2,3,8]],
    [[10,2,0],
    [1,0,2]]
])
print(tensor_tree_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[ 1  5  6]
  [ 2  3  8]]

 [[10  2  0]
  [ 1  0  2]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_tree_d.ndim)

3


Casting

In [ ]:
tensor_one_d = tf.constant([2,0,-3], dtype=tf.float32)
cast_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int16)
print(tensor_one_d)
print(cast_tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int16)


Converter um array para um tensor

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

convert_tensor = tf.convert_to_tensor(np_array)
print(convert_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


Index com tensor

In [ ]:
tensor_index = tf.constant([3,6,2,4,6,66,7])
print(tensor_index)
print(tensor_index[0:4])
print(tensor_index[1:6:2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)


Math Operation

In [ ]:
x_abs = tf.constant([-2.25,65.45])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2.25, 65.45], dtype=float32)>

In [ ]:
tf.sqrt((-2.25)**2 + (-65.45)**2)

<tf.Tensor: shape=(), dtype=float32, numpy=65.48866>

In [ ]:
x_argmax = tf.constant([200,150,45,60])
print(tf.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
x_argmin = tf.constant([200,150,450,60])
print(tf.argmin(x_argmin))

tf.Tensor(3, shape=(), dtype=int64)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False,name=None))

tf.Tensor(35, shape=(), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_max(tensor_two_d, axis=None, keepdims=False,name=None))

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_max(tensor_two_d, axis=0, keepdims=False,name=None))

tf.Tensor([3 5 8], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_min(tensor_two_d, axis=1, keepdims=False,name=None))

tf.Tensor([ 0 -1  1  2], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
], dtype=tf.float16)
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False,name=None))

tf.Tensor([1.75 3.75 3.25], shape=(3,), dtype=float16)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
], dtype=tf.float16)
print(tf.math.reduce_std(tensor_two_d, axis=1, keepdims=False,name=None))

tf.Tensor([0.8164 2.494  2.16   2.625 ], shape=(4,), dtype=float16)


Algebra Linear

Multiplicação entre matriz x1 * x2

In [ ]:
x1 = tf.constant([
    [1,2,3],
    [1,2,3]
])
x2 = tf.constant([
    [1,2],
    [1,2],
    [1,2]
])


In [ ]:
print(x1.shape)
print(x2.shape)

(2, 3)
(3, 2)


In [ ]:
tf.linalg.matmul(
    x1,
    x2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 12],
       [ 6, 12]], dtype=int32)>

In [ ]:
x1@x2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 12],
       [ 6, 12]], dtype=int32)>

Matriz Transposta

In [ ]:
print(x1)
tf.transpose(x1)

tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3]], dtype=int32)>

In [ ]:
print(x2)
tf.transpose(x2)

tf.Tensor(
[[1 2]
 [1 2]
 [1 2]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>

Matriz Inversa

In [ ]:
x = tf.constant([
    [1,2,0],
    [3,5,100],
    [1,5,6]
], dtype=tf.float32)
inv = tf.linalg.inv(x)
print(inv)

tf.Tensor(
[[ 1.5359477   0.03921568 -0.65359473]
 [-0.26797387 -0.01960784  0.3267974 ]
 [-0.03267974  0.00980392  0.00326797]], shape=(3, 3), dtype=float32)


In [ ]:
x@inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.9999994e-01,  0.0000000e+00,  5.9604645e-08],
       [-2.3841858e-07,  9.9999994e-01,  4.9360096e-08],
       [-1.1920929e-07,  0.0000000e+00,  1.0000000e+00]], dtype=float32)>

A decomposição de Matriz

In [ ]:
tf.linalg.svd(x)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100.36639  ,   5.2198467,   0.5840843], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.00135703,  0.41528973,  0.90968823],
        [ 0.99803734, -0.05751522,  0.02476797],
        [ 0.0626068 ,  0.9078693 , -0.41455275]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.03046915,  0.22043058,  0.97492677],
        [ 0.05286566,  0.97365904, -0.22179614],
        [ 0.99813676, -0.05829807, -0.01801335]], dtype=float32)>)

In [ ]:
s,u,v = tf.linalg.svd(x)
print(s)
print(u)
print(v)

tf.Tensor([100.36639     5.2198467   0.5840843], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.00135703  0.41528973  0.90968823]
 [ 0.99803734 -0.05751522  0.02476797]
 [ 0.0626068   0.9078693  -0.41455275]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03046915  0.22043058  0.97492677]
 [ 0.05286566  0.97365904 -0.22179614]
 [ 0.99813676 -0.05829807 -0.01801335]], shape=(3, 3), dtype=float32)


Expandir dimensão de um tensor

In [ ]:
tensor_tree_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],
    [[1,5,6],
    [2,3,8]],
    [[10,2,0],
    [1,0,2]]
])
print(tensor_tree_d.shape)
print(tf.expand_dims(tensor_tree_d,axis=0,name=None).shape)

(3, 2, 3)
(1, 3, 2, 3)


Remover dimensões de um tensor

In [ ]:
x = tf.constant([[2,5,1,3,1]])
print(x.shape)
x_squeze = tf.squeeze(x)
print(x_squeze.shape)
print(x_squeze)

(1, 5)
(5,)
tf.Tensor([2 5 1 3 1], shape=(5,), dtype=int32)


Alterar dimensões de um tensor

In [ ]:
x = tf.constant([
    [[1, 1], [2, 2]],
     [[3, 3], [4, 4]]
])
print(x.shape)
x_reshape = tf.reshape(x,[2,4])
print(x_reshape.shape)
print(x_reshape)

(2, 2, 2)
(2, 4)
tf.Tensor(
[[1 1 2 2]
 [3 3 4 4]], shape=(2, 4), dtype=int32)


Concatenação em tensores

In [ ]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
tf.concat([t1, t2], 0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

Stack de tensor

In [ ]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
tf.stack([x, y, z])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

Preenchimento de tensor

In [ ]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

Coleta de elementos específicos de um tensor

In [ ]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
x = tf.gather(params, indices=[3,1])
y = tf.gather(params, indices=[2,1], axis=1)
print(x)
print(y)

tf.Tensor(
[[30. 31. 32.]
 [10. 11. 12.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 2.  1.]
 [12. 11.]
 [22. 21.]
 [32. 31.]], shape=(4, 2), dtype=float32)


Tensores com dimensões variáveis ou "irregulares"

In [ ]:
x = [
    [1,2,0],
    [3],
    [1,2,3,4,5,6],
    [2,1]]
tensor_ragged = tf.ragged.constant(x)
print(tensor_ragged.shape)

(4, None)


In [ ]:
print(tf.RaggedTensor.from_row_splits(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_splits=[0, 1,2,3, 4, 5,6,7,8]))


<tf.RaggedTensor [[3],
 [1],
 [4],
 [1],
 [5],
 [9],
 [2],
 [6]]>


Tensores esparsos

In [ ]:
tensor_sparse = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [ ]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]], dtype=int32)>